# NumPy 

NumPy (ou Numpy) é uma biblioteca de álgebra linear para Python, a razão pela qual é tão importante para a Data Science com Python é que quase todas as bibliotecas dependem do NumPy como um dos seus principais blocos de construção.

Numpy também é incrivelmente rápido, pois tem ligações para bibliotecas C. Para obter mais informações sobre por que você deseja usar Arrays em vez de listas, confira esta excelente publicação do [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

Nós só aprenderemos os conceitos básicos do NumPy, para começar, precisamos instalá-lo!

## Instruções de instalação

** É altamente recomendável que instale o Python usando a distribuição da Anaconda para garantir que todas as dependências subjacentes (como as bibliotecas de Álgebra Linear) se sincronizem com o uso de uma instalação conda. Se você tiver o Anaconda, instale o NumPy acessando seu terminal ou prompt de comando e digite: **

    conda install numpy
    
** Se você não possui Anaconda e não pode instalá-lo, consulte: [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Usando NumPy

Depois de instalar o NumPy, você pode importá-lo como uma biblioteca:

In [1]:
import numpy as np

Numpy possui muitas funções e capacidades incorporadas. Não vamos cobri-los na totalidade, mas, em vez disso, vamos nos concentrar em alguns dos aspectos mais importantes de Numpy: vetores, arrays, matrizes e geração de números. Comecemos por arrays:

# Numpy Arrays

As matrizes de NumPy são a maneira principal de usar Numpy ao longo do curso. Numpy arrays essencialmente vêm de duas formas: vetores e matrizes. Os vetores são estritamente arranjos de 1d e as matrizes são 2d (mas você deve observar que uma matriz ainda pode ter apenas uma linha ou uma coluna).

Vamos começar nossa introdução explorando como criar matrizes numPy.


## Criando NumPy Arrays

### De uma lista de Python

Podemos criar uma matriz convertendo diretamente uma lista ou lista de listas:

In [2]:
minha_lista = [1,2,3]
minha_lista

[1, 2, 3]

In [6]:
nparr = np.array(minha_lista)
print(type(nparr))
nparr

<class 'numpy.ndarray'>


array([1, 2, 3])

In [3]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
matrixarr = np.array(minha_matriz)
print(type(matrixarr))
matrixarr

<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos incorporados (Built-in Methods)

Há muitas maneiras embutidas de gerar Arrays

### arange

Retorna valores uniformemente espaçados dentro de um determinado intervalo.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros e ones

Gerar matrizes de zeros ou de ums

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Retorna números uniformemente espaçados ao longo de um intervalo especificado.

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Cria uma matriz identidade

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy também tem muitas maneiras de criar arrays de números aleatórios:

### rand
Cria uma matriz da forma dada e preencha com amostras aleatórias de uma distribuição uniforme sobre ``[0, 1)``.

In [15]:
np.random.rand(2,)

array([0.46310211, 0.30925963])

In [16]:
np.random.rand(5,5)

array([[0.18694886, 0.58047071, 0.09885448, 0.52358323, 0.97973963],
       [0.60244317, 0.00605332, 0.80119635, 0.18415312, 0.85963804],
       [0.82699932, 0.27449781, 0.22281129, 0.32124662, 0.13125923],
       [0.64579465, 0.10076754, 0.13993052, 0.57004613, 0.47326577],
       [0.29501505, 0.20527158, 0.10470606, 0.97003571, 0.17090201]])

### randn

Retorna uma amostra (ou amostras) da distribuição "normal". Ao contrário de rand, que é uniforme:

In [17]:
np.random.randn(2)

array([-0.71523483,  0.83098276])

In [41]:
arrN = np.random.randn(5,5)

### randint
Retorna inteiros aleatórios de "low" (inclusive) para "high" (exclusivo).

In [19]:
np.random.randint(1,100)

84

In [20]:
np.random.randint(1,100,10)

array([89, 57, 91, 70, 22, 77, 74, 90, 71, 39])

## Atributos de Array e Métodos

Vamos discutir alguns atributos e métodos úteis ou uma matriz:

In [21]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranarr

array([27,  8, 29,  6, 10, 13, 40, 48, 45,  8])

## Reshape
Retorna uma matriz contendo os mesmos dados com uma nova forma.

In [25]:
print(arr.shape)
print(ranarr.shape)

(25,)
(10,)


In [28]:
print(arr.reshape(25,1).shape)

(25, 1)


In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Estes são métodos úteis para encontrar valores máximos ou mínimos, ou para encontrar seus locais de índice usando argmin ou argmax

In [30]:
ranarr

array([27,  8, 29,  6, 10, 13, 40, 48, 45,  8])

In [31]:
ranarr.max()

48

In [32]:
ranarr.argmax()

7

In [33]:
ranarr.min()

6

In [34]:
ranarr.argmin()

3

## Shape

Shape é um atributo que os arrays têm (não um método):

In [35]:
# Vector
arr.shape

(25,)

In [36]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25).shape

(1, 25)

In [38]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

### dtype
Você também pode pegar o tipo de dados do objeto na matriz:

In [43]:
print(arr.dtype)
arrN.dtype

int32


dtype('float64')